### ISSUE TITLE
KSM tokens in escrow, no avatar transferred

### ISSUE THREAD

**Issue by DJdaSilva** [usetech-llc/substrapunks#8]
Hi!

I am not sure what has happened. I made a purchase on the site and KSM was transferred from my account but the transaction was not completed from the escrow account.

Please see this transaction:
https://polkascan.io/kusama/event/6451684-1

While transaction was completing, the page said there was an error.

This is my first foray into crypto beyond trading on Binance so perhaps I did something wrong?

I first tried transaction before using the telegram faucet. Then I used the Telegram faucet and got a message saying the transfer was successful. Then I proceeded to purchase on the website only to get the error message.

Also when I go to the sell page, it displays an unfamiliar address. On the test network I have no wallet registered so I guess I somehow managed to pay without registering a wallet to receive the avatar?

FYI the address I see on the sell tab is this: 5CyLPGhNjoEQUUGeB6kj62jVNaF7v6NjiDcsVgFrGDUXLwsi

Please help it's a lot of money for me :( any additional info needed please let me know!

**Comment by DJdaSilva** [comment]
Ok I see the unfamiliar wallet address is my NFT test net wallet. So at least wallet shows up now after restarting my browser (interesting ctrl+f5 didn't seem to refresh it) anyway there is still issue of transfer to escrow account not being completed but I feel like this is a step in the right direction at least! Please let me know next steps to fix it....

**Comment by DJdaSilva** [comment]
Ok I am sorted. I browsed the source and fiddled with html a little to get the NFT. I won't close issue in case you want info on process and what happened to iterate. I am technically down 0.2 KSM at this point, price on the NFT dropped from 1.2 to 1 KSM after I purchased and 1 was transferred to the previous owner, meaning there's an extra 0.2 sitting in escrow. It would be nice to maybe split the difference with the previous owner if possible here is the transfer to previous owner:
https://polkascan.io/kusama/event/6457972-1
Like the website, like the fact I was able to get the transaction done so I'm happy to be honest! I may be able to help with improvements thanks to the unfortunate experience. If you are interested please respond otherwise feel free to close!

Thanks!

**Comment by DJdaSilva** [comment]
Processed withdrawal for the 0.2 KSM. 100% square now. Please close unless you want more info. Sorry for the spammy-ness

**Comment by usetech-llc** [comment]
Thank you for your update! Yes, checking with KSMReturn page sorts out most of the problems usually: 

https://ipfs-gateway.usetech.com/ipns/QmaMtDqE9nhMX9RQLTpaCboqg7bqkb6Gi67iCKMe8NDpCE/ksmreturn.html
